name: Linux

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  test:
    runs-on: [ubuntu-latest]
    container:
      image: ubuntu:20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apt update
        apt install -y python3-pytest ninja-build clang-tidy python3-pip clang libgtest-dev python3 libasound2-dev
        pip3 install requests
        pip3 install cmake==3.23.3
        python3 bootstrap.py KuroShinigami318 build_scripts
        chmod +x build_scripts/repo_init.sh
        ./build_scripts/repo_init.sh
    - name: Configure (GCC)
      run: cmake -Bbuild-gcc -DCMAKE_BUILD_TYPE=Debug -G'Ninja Multi-Config'

    - name: Build (GCC, Debug)
      run: cmake --build build-gcc --config Debug

    - name: Build (GCC, Release)
      run: cmake --build build-gcc --config Release

    - name: Configure (Clang)
      run: CC=clang CXX=clang++ cmake -Bbuild-clang -DCMAKE_BUILD_TYPE=Debug -G'Ninja Multi-Config' -DCMAKE_EXPORT_COMPILE_COMMANDS=1

    - name: Build (Clang, Debug)
      run: cmake --build build-clang --config Debug

    - name: Build (Clang, Release)
      run: cmake --build build-clang --config Release

    - name: Build (Clang, RelWithDebInfo)
      run: cmake --build build-clang --config RelWithDebInfo

    - name: clang-tidy
      run: /usr/lib/llvm-10/share/clang/run-clang-tidy.py
      working-directory: build-clang